apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  restartPolicy: Never
  containers:
    - name: config-mapped-container
      image: kubernetesazurefunctionstest
      imagePullPolicy: Never
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: app-1573b95c039e51cc-config
