apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - worker-03e48744252ef722-deployment.yaml
  - worker-03e48744252ef722-service.yaml
  - worker-046b5f12d0ed300f-deployment.yaml
  - worker-046b5f12d0ed300f-service.yaml
  - worker-06da275043bac552-deployment.yaml
  - worker-06da275043bac552-service.yaml
  - worker-0aab83a24e916a30-deployment.yaml
  - worker-0aab83a24e916a30-service.yaml
  - worker-1573b95c039e51cc-deployment.yaml
  - worker-1573b95c039e51cc-service.yaml
  - worker-165156b067e9299a-deployment.yaml
  - worker-165156b067e9299a-service.yaml
  - worker-1661c8faccd5c7ce-deployment.yaml
  - worker-1661c8faccd5c7ce-service.yaml
  - worker-17c37a0fdd5d1932-deployment.yaml
  - worker-17c37a0fdd5d1932-service.yaml
  - worker-18ed3ca44bd1f7d4-deployment.yaml
  - worker-18ed3ca44bd1f7d4-service.yaml
  - worker-1c4353c2703fb166-deployment.yaml
  - worker-1c4353c2703fb166-service.yaml
  - worker-1c5682a8e57d04d0-deployment.yaml
  - worker-1c5682a8e57d04d0-service.yaml
  - worker-1de6db5cc9a0296e-deployment.yaml
  - worker-1de6db5cc9a0296e-service.yaml
  - worker-21e3d223c039daac-deployment.yaml
  - worker-21e3d223c039daac-service.yaml
  - worker-220343d206dfebda-deployment.yaml
  - worker-220343d206dfebda-service.yaml
  - worker-2709aa426c73ec15-deployment.yaml
  - worker-2709aa426c73ec15-service.yaml
  - worker-3029b453646555d8-deployment.yaml
  - worker-3029b453646555d8-service.yaml
  - worker-341a2b2b3affc84b-deployment.yaml
  - worker-341a2b2b3affc84b-service.yaml
  - worker-34bebca9cd2c3d5c-deployment.yaml
  - worker-34bebca9cd2c3d5c-service.yaml
  - worker-37a025445321ed43-deployment.yaml
  - worker-37a025445321ed43-service.yaml
  - worker-38c3814fedc3e476-deployment.yaml
  - worker-38c3814fedc3e476-service.yaml
  - worker-3e325e5d1375e6a6-deployment.yaml
  - worker-3e325e5d1375e6a6-service.yaml
  - worker-3efeb602c2eb29e2-deployment.yaml
  - worker-3efeb602c2eb29e2-service.yaml
  - worker-41b8611922a7e03f-deployment.yaml
  - worker-41b8611922a7e03f-service.yaml
  - worker-458c67821d1d6a60-deployment.yaml
  - worker-458c67821d1d6a60-service.yaml
  - worker-45adb7409f430f55-deployment.yaml
  - worker-45adb7409f430f55-service.yaml
  - worker-4b22cc3e1988174e-deployment.yaml
  - worker-4b22cc3e1988174e-service.yaml
  - worker-4dd59aea96ab30b4-deployment.yaml
  - worker-4dd59aea96ab30b4-service.yaml
  - worker-4f5eafc2b3d6ead5-deployment.yaml
  - worker-4f5eafc2b3d6ead5-service.yaml
  - worker-4f931629ab2497de-deployment.yaml
  - worker-4f931629ab2497de-service.yaml
  - worker-4fd9ef036fda3832-deployment.yaml
  - worker-4fd9ef036fda3832-service.yaml
  - worker-51dbc1cbb708f14d-deployment.yaml
  - worker-51dbc1cbb708f14d-service.yaml
  - worker-530c944fe7e078ff-deployment.yaml
  - worker-530c944fe7e078ff-service.yaml
  - worker-5466ca598a6b68be-deployment.yaml
  - worker-5466ca598a6b68be-service.yaml
  - worker-57d15fc6e7154e6c-deployment.yaml
  - worker-57d15fc6e7154e6c-service.yaml
  - worker-5a214e8e45500489-deployment.yaml
  - worker-5a214e8e45500489-service.yaml
  - worker-5fb02cfeb979fec1-deployment.yaml
  - worker-5fb02cfeb979fec1-service.yaml
  - worker-60bb8c2ce1c44989-deployment.yaml
  - worker-60bb8c2ce1c44989-service.yaml
  - worker-6139f1f15c382fa8-deployment.yaml
  - worker-6139f1f15c382fa8-service.yaml
  - worker-62ed48c098820db0-deployment.yaml
  - worker-62ed48c098820db0-service.yaml
  - worker-641f0f86d3d9f681-deployment.yaml
  - worker-641f0f86d3d9f681-service.yaml
  - worker-64f056310269572d-deployment.yaml
  - worker-64f056310269572d-service.yaml
  - worker-67b406bcce86bae0-deployment.yaml
  - worker-67b406bcce86bae0-service.yaml
  - worker-682c50b946b6efb6-deployment.yaml
  - worker-682c50b946b6efb6-service.yaml
  - worker-68d84244f6a3c212-deployment.yaml
  - worker-68d84244f6a3c212-service.yaml
  - worker-6e42a4e8ea1df408-deployment.yaml
  - worker-6e42a4e8ea1df408-service.yaml
  - worker-70b9cea7ca266637-deployment.yaml
  - worker-70b9cea7ca266637-service.yaml
  - worker-71fab9125e9dc96c-deployment.yaml
  - worker-71fab9125e9dc96c-service.yaml
  - worker-734272c01926d196-deployment.yaml
  - worker-734272c01926d196-service.yaml
  - worker-73e9cf25a1a3b312-deployment.yaml
  - worker-73e9cf25a1a3b312-service.yaml
  - worker-7958f89676bf3653-deployment.yaml
  - worker-7958f89676bf3653-service.yaml
  - worker-7aa2508882a841c9-deployment.yaml
  - worker-7aa2508882a841c9-service.yaml
  - worker-7b2c43a2bc30f6bb-deployment.yaml
  - worker-7b2c43a2bc30f6bb-service.yaml
  - worker-7d37cefc5c5fd0c8-deployment.yaml
  - worker-7d37cefc5c5fd0c8-service.yaml
  - worker-7e425fa87bc12971-deployment.yaml
  - worker-7e425fa87bc12971-service.yaml
  - worker-7fa05b607ae861b8-deployment.yaml
  - worker-7fa05b607ae861b8-service.yaml
  - worker-80ba614b065a6836-deployment.yaml
  - worker-80ba614b065a6836-service.yaml
  - worker-846a33ce84d2b4bf-deployment.yaml
  - worker-846a33ce84d2b4bf-service.yaml
  - worker-85479ef37b5dc75d-deployment.yaml
  - worker-85479ef37b5dc75d-service.yaml
  - worker-85effaac4d59e8d2-deployment.yaml
  - worker-85effaac4d59e8d2-service.yaml
  - worker-8a9817064c66ff2f-deployment.yaml
  - worker-8a9817064c66ff2f-service.yaml
  - worker-8d13ca6c1e7b4541-deployment.yaml
  - worker-8d13ca6c1e7b4541-service.yaml
  - worker-8d5a5cbc5dcaf950-deployment.yaml
  - worker-8d5a5cbc5dcaf950-service.yaml
  - worker-8edcb2c8634528c6-deployment.yaml
  - worker-8edcb2c8634528c6-service.yaml
  - worker-8ef86af9762af347-deployment.yaml
  - worker-8ef86af9762af347-service.yaml
  - worker-8fccbc5264ff823b-deployment.yaml
  - worker-8fccbc5264ff823b-service.yaml
  - worker-938e7f49544b3293-deployment.yaml
  - worker-938e7f49544b3293-service.yaml
  - worker-93b7777259b0d610-deployment.yaml
  - worker-93b7777259b0d610-service.yaml
  - worker-93c57176225d0e98-deployment.yaml
  - worker-93c57176225d0e98-service.yaml
  - worker-9417b97516aa524c-deployment.yaml
  - worker-9417b97516aa524c-service.yaml
  - worker-96149d3ed4f00afb-deployment.yaml
  - worker-96149d3ed4f00afb-service.yaml
  - worker-975dcb62013d897e-deployment.yaml
  - worker-975dcb62013d897e-service.yaml
  - worker-97b9300c3b009d6e-deployment.yaml
  - worker-97b9300c3b009d6e-service.yaml
  - worker-a03d8277f9ec95f7-deployment.yaml
  - worker-a03d8277f9ec95f7-service.yaml
  - worker-a0ed6d33dc4622e0-deployment.yaml
  - worker-a0ed6d33dc4622e0-service.yaml
  - worker-a25e2d58c503c1a3-deployment.yaml
  - worker-a25e2d58c503c1a3-service.yaml
  - worker-a4a3c0390fad6c1a-deployment.yaml
  - worker-a4a3c0390fad6c1a-service.yaml
  - worker-a55aa23d7c2a7c80-deployment.yaml
  - worker-a55aa23d7c2a7c80-service.yaml
  - worker-a594f92f84072b4c-deployment.yaml
  - worker-a594f92f84072b4c-service.yaml
  - worker-a69fc53dccda5042-deployment.yaml
  - worker-a69fc53dccda5042-service.yaml
  - worker-a6bbb3b6d85b46b1-deployment.yaml
  - worker-a6bbb3b6d85b46b1-service.yaml
  - worker-a83894b2184e57e7-deployment.yaml
  - worker-a83894b2184e57e7-service.yaml
  - worker-a9644719e5d173a2-deployment.yaml
  - worker-a9644719e5d173a2-service.yaml
  - worker-a9fd6223e00378ed-deployment.yaml
  - worker-a9fd6223e00378ed-service.yaml
  - worker-abee572c88a5173c-deployment.yaml
  - worker-abee572c88a5173c-service.yaml
  - worker-b1034a4b389601e0-deployment.yaml
  - worker-b1034a4b389601e0-service.yaml
  - worker-b5450811f2226912-deployment.yaml
  - worker-b5450811f2226912-service.yaml
  - worker-b5cd624f4d49f3dc-deployment.yaml
  - worker-b5cd624f4d49f3dc-service.yaml
  - worker-b81ed828cb5e7192-deployment.yaml
  - worker-b81ed828cb5e7192-service.yaml
  - worker-bb0034ea3bcbe045-deployment.yaml
  - worker-bb0034ea3bcbe045-service.yaml
  - worker-bbc455780b7161c4-deployment.yaml
  - worker-bbc455780b7161c4-service.yaml
  - worker-bc11bd0a836eb393-deployment.yaml
  - worker-bc11bd0a836eb393-service.yaml
  - worker-bc378b6d0bed3329-deployment.yaml
  - worker-bc378b6d0bed3329-service.yaml
  - worker-bc7554e7f013bbc9-deployment.yaml
  - worker-bc7554e7f013bbc9-service.yaml
  - worker-c2ea3952c7a77d53-deployment.yaml
  - worker-c2ea3952c7a77d53-service.yaml
  - worker-c6899d1b80112b58-deployment.yaml
  - worker-c6899d1b80112b58-service.yaml
  - worker-c79aae5f316a650e-deployment.yaml
  - worker-c79aae5f316a650e-service.yaml
  - worker-c864b7cf40f389cb-deployment.yaml
  - worker-c864b7cf40f389cb-service.yaml
  - worker-c8c43e1a911f29e5-deployment.yaml
  - worker-c8c43e1a911f29e5-service.yaml
  - worker-ca4fde7aa358b20b-deployment.yaml
  - worker-ca4fde7aa358b20b-service.yaml
  - worker-cd1309cf6db9f944-deployment.yaml
  - worker-cd1309cf6db9f944-service.yaml
  - worker-cebc121403bf0d9d-deployment.yaml
  - worker-cebc121403bf0d9d-service.yaml
  - worker-d27353c8ad7c924a-deployment.yaml
  - worker-d27353c8ad7c924a-service.yaml
  - worker-d399b29c39aafde6-deployment.yaml
  - worker-d399b29c39aafde6-service.yaml
  - worker-d73164944f1fe92f-deployment.yaml
  - worker-d73164944f1fe92f-service.yaml
  - worker-d929e795459178fd-deployment.yaml
  - worker-d929e795459178fd-service.yaml
  - worker-db6be4a997f386b3-deployment.yaml
  - worker-db6be4a997f386b3-service.yaml
  - worker-dd81ee53ae84624a-deployment.yaml
  - worker-dd81ee53ae84624a-service.yaml
  - worker-dfcd50e431bff00c-deployment.yaml
  - worker-dfcd50e431bff00c-service.yaml
  - worker-e6c7bb410627e9eb-deployment.yaml
  - worker-e6c7bb410627e9eb-service.yaml
  - worker-e92487a7ec042235-deployment.yaml
  - worker-e92487a7ec042235-service.yaml
  - worker-ea65064e04faf35c-deployment.yaml
  - worker-ea65064e04faf35c-service.yaml
  - worker-efa202d17ba66651-deployment.yaml
  - worker-efa202d17ba66651-service.yaml
  - worker-f0fa62feeb880620-deployment.yaml
  - worker-f0fa62feeb880620-service.yaml
  - worker-f274d71de386ccc7-deployment.yaml
  - worker-f274d71de386ccc7-service.yaml
  - worker-f7bfe5bc8d2a37a5-deployment.yaml
  - worker-f7bfe5bc8d2a37a5-service.yaml
  - worker-f8a0e46efc7202b8-deployment.yaml
  - worker-f8a0e46efc7202b8-service.yaml
  - worker-fc4cdb6f79037e08-deployment.yaml
  - worker-fc4cdb6f79037e08-service.yaml
  - worker-fcc7dff74ceb0deb-deployment.yaml
  - worker-fcc7dff74ceb0deb-service.yaml
  - worker-fe016d40663e76e9-deployment.yaml
  - worker-fe016d40663e76e9-service.yaml
