apiVersion: v1
kind: Service
metadata:
  name: worker-41b8611922a7e03f
  namespace: default
spec:
  selector:
    app: worker-41b8611922a7e03f
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
