apiVersion: v1
kind: Service
metadata:
  name: worker-c2ea3952c7a77d53
  namespace: default
spec:
  selector:
    app: worker-c2ea3952c7a77d53
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
