apiVersion: v1
kind: Service
metadata:
  name: worker-5a214e8e45500489
  namespace: default
spec:
  selector:
    app: worker-5a214e8e45500489
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
