apiVersion: v1
kind: Service
metadata:
  name: worker-b5cd624f4d49f3dc
  namespace: default
spec:
  selector:
    app: worker-b5cd624f4d49f3dc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
