apiVersion: v1
kind: Service
metadata:
  name: worker-c8c43e1a911f29e5
  namespace: default
spec:
  selector:
    app: worker-c8c43e1a911f29e5
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
