apiVersion: v1
kind: Service
metadata:
  name: worker-846a33ce84d2b4bf
  namespace: default
spec:
  selector:
    app: worker-846a33ce84d2b4bf
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
