apiVersion: v1
kind: Service
metadata:
  name: worker-165156b067e9299a
  namespace: default
spec:
  selector:
    app: worker-165156b067e9299a
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
