apiVersion: v1
kind: Service
metadata:
  name: worker-38c3814fedc3e476
  namespace: default
spec:
  selector:
    app: worker-38c3814fedc3e476
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
