apiVersion: v1
kind: Service
metadata:
  name: worker-046b5f12d0ed300f
  namespace: default
spec:
  selector:
    app: worker-046b5f12d0ed300f
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
