apiVersion: v1
kind: Service
metadata:
  name: worker-06da275043bac552
  namespace: default
spec:
  selector:
    app: worker-06da275043bac552
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
