apiVersion: v1
kind: Service
metadata:
  name: worker-a55aa23d7c2a7c80
  namespace: default
spec:
  selector:
    app: worker-a55aa23d7c2a7c80
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
