apiVersion: v1
kind: Service
metadata:
  name: worker-5fb02cfeb979fec1
  namespace: default
spec:
  selector:
    app: worker-5fb02cfeb979fec1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
