apiVersion: v1
kind: Service
metadata:
  name: worker-bbc455780b7161c4
  namespace: default
spec:
  selector:
    app: worker-bbc455780b7161c4
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
