apiVersion: v1
kind: Service
metadata:
  name: worker-4b22cc3e1988174e
  namespace: default
spec:
  selector:
    app: worker-4b22cc3e1988174e
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
