apiVersion: v1
kind: Service
metadata:
  name: worker-a69fc53dccda5042
  namespace: default
spec:
  selector:
    app: worker-a69fc53dccda5042
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
