apiVersion: v1
kind: Service
metadata:
  name: worker-220343d206dfebda
  namespace: default
spec:
  selector:
    app: worker-220343d206dfebda
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
