apiVersion: v1
kind: Service
metadata:
  name: worker-1573b95c039e51cc
  namespace: default
spec:
  selector:
    app: worker-1573b95c039e51cc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
