apiVersion: v1
kind: Service
metadata:
  name: worker-f7bfe5bc8d2a37a5
  namespace: default
spec:
  selector:
    app: worker-f7bfe5bc8d2a37a5
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
