apiVersion: v1
kind: Service
metadata:
  name: worker-3029b453646555d8
  namespace: default
spec:
  selector:
    app: worker-3029b453646555d8
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
