apiVersion: v1
kind: Service
metadata:
  name: worker-34bebca9cd2c3d5c
  namespace: default
spec:
  selector:
    app: worker-34bebca9cd2c3d5c
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
