apiVersion: v1
kind: Service
metadata:
  name: worker-73e9cf25a1a3b312
  namespace: default
spec:
  selector:
    app: worker-73e9cf25a1a3b312
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
