apiVersion: v1
kind: Service
metadata:
  name: worker-e92487a7ec042235
  namespace: default
spec:
  selector:
    app: worker-e92487a7ec042235
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
