apiVersion: v1
kind: Service
metadata:
  name: worker-a83894b2184e57e7
  namespace: default
spec:
  selector:
    app: worker-a83894b2184e57e7
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
