apiVersion: v1
kind: Service
metadata:
  name: worker-57d15fc6e7154e6c
  namespace: default
spec:
  selector:
    app: worker-57d15fc6e7154e6c
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
