apiVersion: v1
kind: Service
metadata:
  name: worker-bc378b6d0bed3329
  namespace: default
spec:
  selector:
    app: worker-bc378b6d0bed3329
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
