apiVersion: v1
kind: Service
metadata:
  name: worker-458c67821d1d6a60
  namespace: default
spec:
  selector:
    app: worker-458c67821d1d6a60
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
