apiVersion: v1
kind: Service
metadata:
  name: worker-7b2c43a2bc30f6bb
  namespace: default
spec:
  selector:
    app: worker-7b2c43a2bc30f6bb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
