apiVersion: v1
kind: Service
metadata:
  name: worker-3e325e5d1375e6a6
  namespace: default
spec:
  selector:
    app: worker-3e325e5d1375e6a6
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
