apiVersion: v1
kind: Service
metadata:
  name: worker-7e425fa87bc12971
  namespace: default
spec:
  selector:
    app: worker-7e425fa87bc12971
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
