apiVersion: v1
kind: Service
metadata:
  name: worker-fcc7dff74ceb0deb
  namespace: default
spec:
  selector:
    app: worker-fcc7dff74ceb0deb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
