apiVersion: v1
kind: Service
metadata:
  name: worker-abee572c88a5173c
  namespace: default
spec:
  selector:
    app: worker-abee572c88a5173c
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
