apiVersion: v1
kind: Service
metadata:
  name: worker-7aa2508882a841c9
  namespace: default
spec:
  selector:
    app: worker-7aa2508882a841c9
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
