apiVersion: v1
kind: Service
metadata:
  name: worker-4dd59aea96ab30b4
  namespace: default
spec:
  selector:
    app: worker-4dd59aea96ab30b4
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
