apiVersion: v1
kind: Service
metadata:
  name: worker-96149d3ed4f00afb
  namespace: default
spec:
  selector:
    app: worker-96149d3ed4f00afb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
