apiVersion: v1
kind: Service
metadata:
  name: worker-a25e2d58c503c1a3
  namespace: default
spec:
  selector:
    app: worker-a25e2d58c503c1a3
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
