apiVersion: v1
kind: Service
metadata:
  name: worker-17c37a0fdd5d1932
  namespace: default
spec:
  selector:
    app: worker-17c37a0fdd5d1932
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
