apiVersion: v1
kind: Service
metadata:
  name: worker-80ba614b065a6836
  namespace: default
spec:
  selector:
    app: worker-80ba614b065a6836
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
