apiVersion: v1
kind: Service
metadata:
  name: worker-cd1309cf6db9f944
  namespace: default
spec:
  selector:
    app: worker-cd1309cf6db9f944
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
