apiVersion: v1
kind: Service
metadata:
  name: worker-03e48744252ef722
  namespace: default
spec:
  selector:
    app: worker-03e48744252ef722
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
