apiVersion: v1
kind: Service
metadata:
  name: worker-b81ed828cb5e7192
  namespace: default
spec:
  selector:
    app: worker-b81ed828cb5e7192
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
