apiVersion: v1
kind: Service
metadata:
  name: worker-7fa05b607ae861b8
  namespace: default
spec:
  selector:
    app: worker-7fa05b607ae861b8
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
