apiVersion: v1
kind: Service
metadata:
  name: worker-3efeb602c2eb29e2
  namespace: default
spec:
  selector:
    app: worker-3efeb602c2eb29e2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
