apiVersion: v1
kind: Service
metadata:
  name: worker-64f056310269572d
  namespace: default
spec:
  selector:
    app: worker-64f056310269572d
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
