apiVersion: v1
kind: Service
metadata:
  name: worker-fe016d40663e76e9
  namespace: default
spec:
  selector:
    app: worker-fe016d40663e76e9
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
