apiVersion: v1
kind: Service
metadata:
  name: worker-b1034a4b389601e0
  namespace: default
spec:
  selector:
    app: worker-b1034a4b389601e0
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
