apiVersion: v1
kind: Service
metadata:
  name: worker-93b7777259b0d610
  namespace: default
spec:
  selector:
    app: worker-93b7777259b0d610
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
