apiVersion: v1
kind: Service
metadata:
  name: worker-682c50b946b6efb6
  namespace: default
spec:
  selector:
    app: worker-682c50b946b6efb6
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
