apiVersion: v1
kind: Service
metadata:
  name: worker-8d5a5cbc5dcaf950
  namespace: default
spec:
  selector:
    app: worker-8d5a5cbc5dcaf950
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
