apiVersion: v1
kind: Service
metadata:
  name: worker-8fccbc5264ff823b
  namespace: default
spec:
  selector:
    app: worker-8fccbc5264ff823b
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
