apiVersion: v1
kind: Service
metadata:
  name: worker-8ef86af9762af347
  namespace: default
spec:
  selector:
    app: worker-8ef86af9762af347
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
