apiVersion: v1
kind: Service
metadata:
  name: worker-db6be4a997f386b3
  namespace: default
spec:
  selector:
    app: worker-db6be4a997f386b3
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
