apiVersion: v1
kind: Service
metadata:
  name: worker-60bb8c2ce1c44989
  namespace: default
spec:
  selector:
    app: worker-60bb8c2ce1c44989
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
