apiVersion: v1
kind: Service
metadata:
  name: worker-1c5682a8e57d04d0
  namespace: default
spec:
  selector:
    app: worker-1c5682a8e57d04d0
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
