apiVersion: v1
kind: Service
metadata:
  name: worker-21e3d223c039daac
  namespace: default
spec:
  selector:
    app: worker-21e3d223c039daac
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
