apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: app-7b2c43a2bc30f6bb-config
    files:
      - configs/app-7b2c43a2bc30f6bb/schedule.json
  - name: app-1573b95c039e51cc-config
    files:
      - configs/app-1573b95c039e51cc/schedule.json
  - name: app-f274d71de386ccc7-config
    files:
      - configs/app-f274d71de386ccc7/schedule.json
  - name: app-f7bfe5bc8d2a37a5-config
    files:
      - configs/app-f7bfe5bc8d2a37a5/schedule.json
  - name: app-85479ef37b5dc75d-config
    files:
      - configs/app-85479ef37b5dc75d/schedule.json
