apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - worker-04605a37a22e0509-deployment.yaml
  - worker-04605a37a22e0509-service.yaml
  - worker-063ba6f3c1d425f6-deployment.yaml
  - worker-063ba6f3c1d425f6-service.yaml
  - worker-0ce67779eaa33056-deployment.yaml
  - worker-0ce67779eaa33056-service.yaml
  - worker-1992918c23cc9224-deployment.yaml
  - worker-1992918c23cc9224-service.yaml
  - worker-2b373145c4fa2c34-deployment.yaml
  - worker-2b373145c4fa2c34-service.yaml
  - worker-308ecb6c8592f6f8-deployment.yaml
  - worker-308ecb6c8592f6f8-service.yaml
  - worker-31778f4c7f71ba17-deployment.yaml
  - worker-31778f4c7f71ba17-service.yaml
  - worker-3e29f84dda113c04-deployment.yaml
  - worker-3e29f84dda113c04-service.yaml
  - worker-4456b981d48aae1e-deployment.yaml
  - worker-4456b981d48aae1e-service.yaml
  - worker-47658c9cff05caaf-deployment.yaml
  - worker-47658c9cff05caaf-service.yaml
  - worker-4fec01ac4ad62bb7-deployment.yaml
  - worker-4fec01ac4ad62bb7-service.yaml
  - worker-5315be05fc3b21a3-deployment.yaml
  - worker-5315be05fc3b21a3-service.yaml
  - worker-5336bda8faa5d11b-deployment.yaml
  - worker-5336bda8faa5d11b-service.yaml
  - worker-5452242012899b0b-deployment.yaml
  - worker-5452242012899b0b-service.yaml
  - worker-5608f70ad5c4f89e-deployment.yaml
  - worker-5608f70ad5c4f89e-service.yaml
  - worker-64defca3c186f3ca-deployment.yaml
  - worker-64defca3c186f3ca-service.yaml
  - worker-6590c82e22abcdaf-deployment.yaml
  - worker-6590c82e22abcdaf-service.yaml
  - worker-65c4bf1b7fe6a779-deployment.yaml
  - worker-65c4bf1b7fe6a779-service.yaml
  - worker-660323aa6f1012c8-deployment.yaml
  - worker-660323aa6f1012c8-service.yaml
  - worker-68c45f54d6dd3861-deployment.yaml
  - worker-68c45f54d6dd3861-service.yaml
  - worker-711b0aab9f246bb3-deployment.yaml
  - worker-711b0aab9f246bb3-service.yaml
  - worker-7967443fae241b40-deployment.yaml
  - worker-7967443fae241b40-service.yaml
  - worker-8203ff88388384a6-deployment.yaml
  - worker-8203ff88388384a6-service.yaml
  - worker-8c9ce0de516e04d5-deployment.yaml
  - worker-8c9ce0de516e04d5-service.yaml
  - worker-93d4c31373200d74-deployment.yaml
  - worker-93d4c31373200d74-service.yaml
  - worker-9bce5e2ee302cba4-deployment.yaml
  - worker-9bce5e2ee302cba4-service.yaml
  - worker-9d133e10efe8865e-deployment.yaml
  - worker-9d133e10efe8865e-service.yaml
  - worker-9f7c42b1b5e58255-deployment.yaml
  - worker-9f7c42b1b5e58255-service.yaml
  - worker-b1224a9c879b3aa7-deployment.yaml
  - worker-b1224a9c879b3aa7-service.yaml
  - worker-b200945b3dd7c23a-deployment.yaml
  - worker-b200945b3dd7c23a-service.yaml
  - worker-ca18283c1b4dd579-deployment.yaml
  - worker-ca18283c1b4dd579-service.yaml
  - worker-cba2d4a3cb55d92a-deployment.yaml
  - worker-cba2d4a3cb55d92a-service.yaml
  - worker-dc460935782ecb98-deployment.yaml
  - worker-dc460935782ecb98-service.yaml
  - worker-dd833bb70b3a57ca-deployment.yaml
  - worker-dd833bb70b3a57ca-service.yaml
  - worker-e9d75b347d07708f-deployment.yaml
  - worker-e9d75b347d07708f-service.yaml
  - worker-ea885ffca6338a2b-deployment.yaml
  - worker-ea885ffca6338a2b-service.yaml
  - worker-f49c9b07fabac545-deployment.yaml
  - worker-f49c9b07fabac545-service.yaml
  - worker-f70c357bc8f4449d-deployment.yaml
  - worker-f70c357bc8f4449d-service.yaml
  - worker-f8c5d1ba78b7d2f4-deployment.yaml
  - worker-f8c5d1ba78b7d2f4-service.yaml
  - worker-fd87c379a4f2dac5-deployment.yaml
  - worker-fd87c379a4f2dac5-service.yaml
