apiVersion: v1
kind: Service
metadata:
  name: worker-85479ef37b5d-1f33077bb2db
  namespace: default
spec:
  selector:
    app: worker-85479ef37b5d-1f33077bb2db
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
