apiVersion: v1
kind: Service
metadata:
  name: worker-04605a37a22e0509
  namespace: default
spec:
  selector:
    app: worker-04605a37a22e0509
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
