apiVersion: v1
kind: Service
metadata:
  name: worker-ca18283c1b4dd579
  namespace: default
spec:
  selector:
    app: worker-ca18283c1b4dd579
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
