apiVersion: v1
kind: Service
metadata:
  name: worker-5608f70ad5c4f89e
  namespace: default
spec:
  selector:
    app: worker-5608f70ad5c4f89e
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
