apiVersion: v1
kind: Service
metadata:
  name: worker-8203ff88388384a6
  namespace: default
spec:
  selector:
    app: worker-8203ff88388384a6
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
