apiVersion: v1
kind: Service
metadata:
  name: worker-18ed3ca44bd1-97d6075b5c2b
  namespace: default
spec:
  selector:
    app: worker-18ed3ca44bd1-97d6075b5c2b
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
