apiVersion: v1
kind: Service
metadata:
  name: worker-660323aa6f1012c8
  namespace: default
spec:
  selector:
    app: worker-660323aa6f1012c8
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
