apiVersion: v1
kind: Service
metadata:
  name: worker-64defca3c186f3ca
  namespace: default
spec:
  selector:
    app: worker-64defca3c186f3ca
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
