apiVersion: v1
kind: Service
metadata:
  name: worker-7b2c43a2bc30-68bbfd828223
  namespace: default
spec:
  selector:
    app: worker-7b2c43a2bc30-68bbfd828223
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
