apiVersion: v1
kind: Service
metadata:
  name: worker-5315be05fc3b21a3
  namespace: default
spec:
  selector:
    app: worker-5315be05fc3b21a3
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
