apiVersion: v1
kind: Service
metadata:
  name: worker-4fd9ef036fda-dea190b390aa
  namespace: default
spec:
  selector:
    app: worker-4fd9ef036fda-dea190b390aa
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
