apiVersion: v1
kind: Service
metadata:
  name: worker-fd87c379a4f2dac5
  namespace: default
spec:
  selector:
    app: worker-fd87c379a4f2dac5
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
