apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-18ed3ca44bd1-97d6075b5c2b
  namespace: default
  labels:
    app: worker-18ed3ca44bd1-97d6075b5c2b
    role: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-18ed3ca44bd1-97d6075b5c2b
  template:
    metadata:
      labels:
        app: worker-18ed3ca44bd1-97d6075b5c2b
        role: worker
    spec:
      nodeSelector:
        topology.kubernetes.io/node-name: alpha
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
      containers:
        - name: worker
          image: nobbertins/worker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
