apiVersion: v1
kind: Service
metadata:
  name: worker-c8c43e1a911f-653cdbc309bc
  namespace: default
spec:
  selector:
    app: worker-c8c43e1a911f-653cdbc309bc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
