apiVersion: v1
kind: Service
metadata:
  name: worker-93d4c31373200d74
  namespace: default
spec:
  selector:
    app: worker-93d4c31373200d74
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
