apiVersion: v1
kind: Service
metadata:
  name: worker-dc460935782ecb98
  namespace: default
spec:
  selector:
    app: worker-dc460935782ecb98
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
