apiVersion: v1
kind: Service
metadata:
  name: worker-17c37a0fdd5d-c9f8e30e36d1
  namespace: default
spec:
  selector:
    app: worker-17c37a0fdd5d-c9f8e30e36d1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
