apiVersion: v1
kind: Service
metadata:
  name: worker-063ba6f3c1d425f6
  namespace: default
spec:
  selector:
    app: worker-063ba6f3c1d425f6
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
