apiVersion: v1
kind: Service
metadata:
  name: worker-308ecb6c8592f6f8
  namespace: default
spec:
  selector:
    app: worker-308ecb6c8592f6f8
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
