apiVersion: v1
kind: Service
metadata:
  name: worker-68c45f54d6dd3861
  namespace: default
spec:
  selector:
    app: worker-68c45f54d6dd3861
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
