apiVersion: v1
kind: Service
metadata:
  name: worker-68d84244f6a3-ca8b2d1318a1
  namespace: default
spec:
  selector:
    app: worker-68d84244f6a3-ca8b2d1318a1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
