apiVersion: v1
kind: Service
metadata:
  name: worker-cba2d4a3cb55d92a
  namespace: default
spec:
  selector:
    app: worker-cba2d4a3cb55d92a
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
